# Generated by Django 5.2.3 on 2025-06-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('reporter', 'Reporter'), ('reviewer', 'Reviewer'), ('admin', 'Admin')], default='reporter', max_length=20),
        ),
    ]
