# Generated by Django 5.2.3 on 2025-07-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
